# Generated by Django 4.2.7 on 2023-11-24 17:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(db_index=True, max_length=100, verbose_name='Автор')),
                ('birthday', models.DateTimeField(auto_now_add=True, verbose_name='Дата рождение')),
                ('biography', models.TextField(blank=True, verbose_name='биография')),
                ('image', models.ImageField(blank=True, upload_to='books', verbose_name=' фото')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Государство')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(db_column='Жанр', max_length=100, unique=True, verbose_name='Жанр')),
                ('description', models.TextField(db_column='Описание', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_publisher', models.CharField(max_length=100, verbose_name='Название издательства')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'издательства',
                'verbose_name_plural': 'издательства',
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100, verbose_name='имя читатель')),
                ('age', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='возрост ')),
            ],
            options={
                'verbose_name': 'читатель',
                'verbose_name_plural': 'читатели',
                'db_table': 'reader',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=100, unique=True, verbose_name='Название книги')),
                ('image', models.ImageField(upload_to='books', verbose_name=' фото')),
                ('quantity_page', models.PositiveSmallIntegerField(blank=True, verbose_name='Количество страниц')),
                ('date_publish', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('text_book', models.TextField(blank=True, verbose_name='содержания книги')),
                ('author', models.ManyToManyField(related_name='aut', to='books.author', verbose_name='Автор')),
                ('country', models.ManyToManyField(to='books.country', verbose_name='Страна')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre_id', to='books.genre', verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'book',
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ManyToManyField(to='books.country', verbose_name='Страна'),
        ),
    ]
