# Generated by Django 4.2.7 on 2023-11-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_country_options_alter_country_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='text_book',
            field=models.FileField(blank=True, upload_to='file/', verbose_name='содержания книги'),
        ),
    ]
