# Generated by Django 4.2.7 on 2023-11-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_text_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text_book',
            field=models.FileField(blank=True, upload_to='file/', verbose_name='файл'),
        ),
    ]
