# Generated by Django 4.2.7 on 2023-11-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_reader_email_alter_book_text_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Слаг'),
        ),
    ]
